---
# docker dependencies

- name: Download docker asc key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add postgresql repository to source list
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ "amd64" if ansible_architecture == "x86_64" }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    update_cache: false
    state: present
