---
# docker setup

- name: Get a /list of sudo users
  ansible.builtin.getent:
    database: group
    key: sudo
  register: sudo_users

- name: Add sudo users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ sudo_users.ansible_facts.getent_group.sudo[2:][0].split(',') }}"